site_name: pygeoapi
site_description: "pygeoapi: an OGC API to geospatial data"
site_author: the pygeoapi community
copyright: "&copy; 2019 - 2020 Tom Kralidis"
site_url: https://pygeoapi.io
repo_url: https://github.com/geopython/pygeoapi.io
docs_dir: docs

nav:
    - Home: index.md
    - Community: community/index.md
    - Documentation: documentation.md
    - Demo: https://demo.pygeoapi.io
    - Code: https://github.com/geopython/pygeoapi
    - Download: download.md
    - Development: development/index.md

use_directory_urls: true

theme:
    name: null
    custom_dir: pygeoapi.io-theme

plugins:
    - search
